# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20180125_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-updated_at']},
        ),
    ]
